# Generated by Django 5.1.3 on 2024-11-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='multiplicador',
            field=models.IntegerField(default=10),
        ),
    ]
