# Generated by Django 5.1.3 on 2024-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_difficulty_multiplicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficulty',
            name='multiplicador',
        ),
    ]
